/** Settings panel shared constants. */

export const MAX_TIMEZONE_RESULTS = 80

export const FALLBACK_TIMEZONES = [
  'UTC',
  'Atlantic/Reykjavik',
  'Europe/London',
  'Europe/Dublin',
  'Europe/Lisbon',
  'Europe/Paris',
  'Europe/Brussels',
  'Europe/Berlin',
  'Europe/Amsterdam',
  'Europe/Stockholm',
  'Europe/Madrid',
  'Europe/Rome',
  'Europe/Warsaw',
  'Europe/Athens',
  'Europe/Helsinki',
  'Europe/Istanbul',
  'Europe/Moscow',
  'Africa/Cairo',
  'Africa/Johannesburg',
  'Asia/Jerusalem',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Kathmandu',
  'Asia/Bangkok',
  'Asia/Ho_Chi_Minh',
  'Asia/Jakarta',
  'Asia/Shanghai',
  'Asia/Hong_Kong',
  'Asia/Taipei',
  'Asia/Singapore',
  'Asia/Kuala_Lumpur',
  'Asia/Manila',
  'Asia/Seoul',
  'Asia/Tokyo',
  'Asia/Colombo',
  'Asia/Karachi',
  'Asia/Tashkent',
  'Australia/Perth',
  'Australia/Adelaide',
  'Australia/Sydney',
  'Pacific/Auckland',
  'Pacific/Honolulu',
  'America/Anchorage',
  'America/Los_Angeles',
  'America/Denver',
  'America/Phoenix',
  'America/Chicago',
  'America/New_York',
  'America/Toronto',
  'America/Halifax',
  'America/St_Johns',
  'America/Mexico_City',
  'America/Bogota',
  'America/Lima',
  'America/Santiago',
  'America/Sao_Paulo',
  'America/Argentina/Buenos_Aires',
  'America/Montevideo',
  'America/Caracas',
  'America/Panama',
  'Indian/Mauritius',
  'Indian/Maldives',
]

/** Defined at module level so they don't get re-created on every render. */
export const WIDGET_DEFS = [
  { id: 'weather', label: 'Weather', description: 'Current conditions for your selected city.' },
  { id: 'todo', label: 'Todo List', description: 'Track and complete tasks. Persists locally.' },
  { id: 'pomodoro', label: 'Pomodoro', description: 'Focus and break cycles with a local timer.' },
  { id: 'dailyFocus', label: "Today's Focus", description: 'Single daily goal. Resets at midnight.' },
  { id: 'quote', label: 'Daily Quote', description: 'Fresh quote each day from a bundled set.' },
]

export const POMODORO_DEFS = [
  { label: 'Focus', key: 'focus', default: 25 },
  { label: 'Short Break', key: 'shortBreak', default: 5 },
  { label: 'Long Break', key: 'longBreak', default: 15 },
]

export const DEFAULT_POMODORO_DURATIONS = { focus: 25, shortBreak: 5, longBreak: 15 }
